//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/CT.WCF_Service")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSService.ReturnStatusCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSService.BankRequestVM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSService.CurrencyRequestVM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSService.AuthServiceRequestVM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSService.SendEmailVM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSService.LogPcrVM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSService.LogVM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SMSService.DashboardRequestVM))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    public partial class ServiceResult : object
    {
        
        private SMSService.ReturnStatusCode ResultCodeField;
        
        private string ResultMessageField;
        
        private object ResultObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SMSService.ReturnStatusCode ResultCode
        {
            get
            {
                return this.ResultCodeField;
            }
            set
            {
                this.ResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultMessage
        {
            get
            {
                return this.ResultMessageField;
            }
            set
            {
                this.ResultMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ResultObject
        {
            get
            {
                return this.ResultObjectField;
            }
            set
            {
                this.ResultObjectField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnStatusCode", Namespace="http://schemas.datacontract.org/2004/07/CT_Common.Enums")]
    public enum ReturnStatusCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DbSelectError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DbUpdateError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DbInsertError = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DbGeneralError = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccesDenided = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadRequest = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourseRed = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InsufficientBalance = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyTopLimitExceeded = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotVerifiedSmsCode = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotVerifiedKkbPinCode = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorRaporTeslimXML = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GsmNoDogrulanmadi = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AynıCode = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BaskasiTarafindanKullanilanGsmNo = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CTApiAuthorizationError = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameOrPasswordIncorrect = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CTSirketPaneliHesabiAktifDegil = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CTSirketSaticiHesabiAktifDegil = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormValidationError = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CTPanelUsernameOrPasswordIncorrect = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CrifPanelHesabiAktifDegil = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApiNeverRequest = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnKnown = 100,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankRequestVM", Namespace="http://schemas.datacontract.org/2004/07/CT_Models.VMs.General")]
    public partial class BankRequestVM : object
    {
        
        private System.Nullable<int> IDField;
        
        private System.Nullable<int> MbCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MbCode
        {
            get
            {
                return this.MbCodeField;
            }
            set
            {
                this.MbCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyRequestVM", Namespace="http://schemas.datacontract.org/2004/07/CT_Models.VMs.General")]
    public partial class CurrencyRequestVM : object
    {
        
        private System.Nullable<int> IDField;
        
        private string ShortNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName
        {
            get
            {
                return this.ShortNameField;
            }
            set
            {
                this.ShortNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthServiceRequestVM", Namespace="http://schemas.datacontract.org/2004/07/CT_Models.VMs.General")]
    public partial class AuthServiceRequestVM : object
    {
        
        private string CtWcfpasswordField;
        
        private string CtWcfusernameField;
        
        private string IpAddressField;
        
        private System.Nullable<long> ShopperIDField;
        
        private System.Nullable<int> UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CtWcfpassword
        {
            get
            {
                return this.CtWcfpasswordField;
            }
            set
            {
                this.CtWcfpasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CtWcfusername
        {
            get
            {
                return this.CtWcfusernameField;
            }
            set
            {
                this.CtWcfusernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress
        {
            get
            {
                return this.IpAddressField;
            }
            set
            {
                this.IpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ShopperID
        {
            get
            {
                return this.ShopperIDField;
            }
            set
            {
                this.ShopperIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendEmailVM", Namespace="http://schemas.datacontract.org/2004/07/CT_Models.VMs.General")]
    public partial class SendEmailVM : object
    {
        
        private System.Nullable<int> CreatedByField;
        
        private string MessageField;
        
        private string SendAlsoToField;
        
        private string SubjectField;
        
        private string ToEmailField;
        
        private string ToNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendAlsoTo
        {
            get
            {
                return this.SendAlsoToField;
            }
            set
            {
                this.SendAlsoToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToEmail
        {
            get
            {
                return this.ToEmailField;
            }
            set
            {
                this.ToEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToName
        {
            get
            {
                return this.ToNameField;
            }
            set
            {
                this.ToNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogPcrVM", Namespace="http://schemas.datacontract.org/2004/07/CT_Models.VMs.General")]
    public partial class LogPcrVM : object
    {
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string NameField;
        
        private int PaymentChannelIDField;
        
        private string ReqDetailsField;
        
        private string RespDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentChannelID
        {
            get
            {
                return this.PaymentChannelIDField;
            }
            set
            {
                this.PaymentChannelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReqDetails
        {
            get
            {
                return this.ReqDetailsField;
            }
            set
            {
                this.ReqDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RespDetails
        {
            get
            {
                return this.RespDetailsField;
            }
            set
            {
                this.RespDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogVM", Namespace="http://schemas.datacontract.org/2004/07/CT_Models.VMs.General")]
    public partial class LogVM : object
    {
        
        private System.Nullable<int> CompanyAdminIDField;
        
        private System.Nullable<int> CrifAdminIDField;
        
        private string DetailsField;
        
        private string IpAddressField;
        
        private bool IsErrorField;
        
        private string NameField;
        
        private System.Nullable<long> ShopperIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyAdminID
        {
            get
            {
                return this.CompanyAdminIDField;
            }
            set
            {
                this.CompanyAdminIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CrifAdminID
        {
            get
            {
                return this.CrifAdminIDField;
            }
            set
            {
                this.CrifAdminIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress
        {
            get
            {
                return this.IpAddressField;
            }
            set
            {
                this.IpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError
        {
            get
            {
                return this.IsErrorField;
            }
            set
            {
                this.IsErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ShopperID
        {
            get
            {
                return this.ShopperIDField;
            }
            set
            {
                this.ShopperIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DashboardRequestVM", Namespace="http://schemas.datacontract.org/2004/07/CT_Models.VMs.General")]
    public partial class DashboardRequestVM : object
    {
        
        private int[] dealerIDField;
        
        private System.DateTime endDateField;
        
        private string orderByField;
        
        private System.DateTime startDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] dealerID
        {
            get
            {
                return this.dealerIDField;
            }
            set
            {
                this.dealerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderBy
        {
            get
            {
                return this.orderByField;
            }
            set
            {
                this.orderByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSService.IAllGeneralService")]
    public interface IAllGeneralService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/BankList", ReplyAction="http://tempuri.org/IAllGeneralService/BankListResponse")]
        System.Threading.Tasks.Task<SMSService.BankListResponse> BankListAsync(SMSService.BankListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/GetBank", ReplyAction="http://tempuri.org/IAllGeneralService/GetBankResponse")]
        System.Threading.Tasks.Task<SMSService.GetBankResponse> GetBankAsync(SMSService.GetBankRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/CurrencyList", ReplyAction="http://tempuri.org/IAllGeneralService/CurrencyListResponse")]
        System.Threading.Tasks.Task<SMSService.CurrencyListResponse> CurrencyListAsync(SMSService.CurrencyListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/GetCurrency", ReplyAction="http://tempuri.org/IAllGeneralService/GetCurrencyResponse")]
        System.Threading.Tasks.Task<SMSService.GetCurrencyResponse> GetCurrencyAsync(SMSService.GetCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/LanguageList", ReplyAction="http://tempuri.org/IAllGeneralService/LanguageListResponse")]
        System.Threading.Tasks.Task<SMSService.LanguageListResponse> LanguageListAsync(SMSService.LanguageListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/CountryList", ReplyAction="http://tempuri.org/IAllGeneralService/CountryListResponse")]
        System.Threading.Tasks.Task<SMSService.CountryListResponse> CountryListAsync(SMSService.CountryListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/CityList", ReplyAction="http://tempuri.org/IAllGeneralService/CityListResponse")]
        System.Threading.Tasks.Task<SMSService.CityListResponse> CityListAsync(SMSService.CityListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/CompanyList", ReplyAction="http://tempuri.org/IAllGeneralService/CompanyListResponse")]
        System.Threading.Tasks.Task<SMSService.CompanyListResponse> CompanyListAsync(SMSService.CompanyListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/SendSmsManuel", ReplyAction="http://tempuri.org/IAllGeneralService/SendSmsManuelResponse")]
        System.Threading.Tasks.Task<SMSService.SendSmsManuelResponse> SendSmsManuelAsync(SMSService.SendSmsManuelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/SendEmailManuel", ReplyAction="http://tempuri.org/IAllGeneralService/SendEmailManuelResponse")]
        System.Threading.Tasks.Task<SMSService.SendEmailManuelResponse> SendEmailManuelAsync(SMSService.SendEmailManuelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/PaymentChannelServiceLoguOlustur", ReplyAction="http://tempuri.org/IAllGeneralService/PaymentChannelServiceLoguOlusturResponse")]
        System.Threading.Tasks.Task<SMSService.PaymentChannelServiceLoguOlusturResponse> PaymentChannelServiceLoguOlusturAsync(SMSService.PaymentChannelServiceLoguOlusturRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/HataLoguOlustur", ReplyAction="http://tempuri.org/IAllGeneralService/HataLoguOlusturResponse")]
        System.Threading.Tasks.Task<SMSService.HataLoguOlusturResponse> HataLoguOlusturAsync(SMSService.HataLoguOlusturRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/InfoLoguOlustur", ReplyAction="http://tempuri.org/IAllGeneralService/InfoLoguOlusturResponse")]
        System.Threading.Tasks.Task<SMSService.InfoLoguOlusturResponse> InfoLoguOlusturAsync(SMSService.InfoLoguOlusturRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/GetDashboard", ReplyAction="http://tempuri.org/IAllGeneralService/GetDashboardResponse")]
        System.Threading.Tasks.Task<SMSService.GetDashboardResponse> GetDashboardAsync(SMSService.GetDashboardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllGeneralService/GetDashboardShopperTopList", ReplyAction="http://tempuri.org/IAllGeneralService/GetDashboardShopperTopListResponse")]
        System.Threading.Tasks.Task<SMSService.GetDashboardShopperTopListResponse> GetDashboardShopperTopListAsync(SMSService.GetDashboardShopperTopListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BankList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BankListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        public BankListRequest()
        {
        }
        
        public BankListRequest(string CtWcfusername, string CtWcfpassword)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BankListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BankListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult BankListResult;
        
        public BankListResponse()
        {
        }
        
        public BankListResponse(SMSService.ServiceResult BankListResult)
        {
            this.BankListResult = BankListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBank", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBankRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public SMSService.BankRequestVM req;
        
        public GetBankRequest()
        {
        }
        
        public GetBankRequest(string CtWcfusername, string CtWcfpassword, SMSService.BankRequestVM req)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBankResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBankResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult GetBankResult;
        
        public GetBankResponse()
        {
        }
        
        public GetBankResponse(SMSService.ServiceResult GetBankResult)
        {
            this.GetBankResult = GetBankResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CurrencyList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CurrencyListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        public CurrencyListRequest()
        {
        }
        
        public CurrencyListRequest(string CtWcfusername, string CtWcfpassword)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CurrencyListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CurrencyListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult CurrencyListResult;
        
        public CurrencyListResponse()
        {
        }
        
        public CurrencyListResponse(SMSService.ServiceResult CurrencyListResult)
        {
            this.CurrencyListResult = CurrencyListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrency", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCurrencyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public SMSService.CurrencyRequestVM req;
        
        public GetCurrencyRequest()
        {
        }
        
        public GetCurrencyRequest(string CtWcfusername, string CtWcfpassword, SMSService.CurrencyRequestVM req)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrencyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCurrencyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult GetCurrencyResult;
        
        public GetCurrencyResponse()
        {
        }
        
        public GetCurrencyResponse(SMSService.ServiceResult GetCurrencyResult)
        {
            this.GetCurrencyResult = GetCurrencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LanguageList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LanguageListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        public LanguageListRequest()
        {
        }
        
        public LanguageListRequest(string CtWcfusername, string CtWcfpassword)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LanguageListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LanguageListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult LanguageListResult;
        
        public LanguageListResponse()
        {
        }
        
        public LanguageListResponse(SMSService.ServiceResult LanguageListResult)
        {
            this.LanguageListResult = LanguageListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountryList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CountryListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        public CountryListRequest()
        {
        }
        
        public CountryListRequest(string CtWcfusername, string CtWcfpassword)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CountryListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CountryListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult CountryListResult;
        
        public CountryListResponse()
        {
        }
        
        public CountryListResponse(SMSService.ServiceResult CountryListResult)
        {
            this.CountryListResult = CountryListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CityList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CityListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        public CityListRequest()
        {
        }
        
        public CityListRequest(string CtWcfusername, string CtWcfpassword)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CityListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CityListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult CityListResult;
        
        public CityListResponse()
        {
        }
        
        public CityListResponse(SMSService.ServiceResult CityListResult)
        {
            this.CityListResult = CityListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CompanyList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CompanyListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        public CompanyListRequest()
        {
        }
        
        public CompanyListRequest(string CtWcfusername, string CtWcfpassword)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CompanyListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CompanyListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult CompanyListResult;
        
        public CompanyListResponse()
        {
        }
        
        public CompanyListResponse(SMSService.ServiceResult CompanyListResult)
        {
            this.CompanyListResult = CompanyListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSmsManuel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsManuelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.AuthServiceRequestVM auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string _mobileNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string _message;
        
        public SendSmsManuelRequest()
        {
        }
        
        public SendSmsManuelRequest(SMSService.AuthServiceRequestVM auth, string _mobileNumber, string _message)
        {
            this.auth = auth;
            this._mobileNumber = _mobileNumber;
            this._message = _message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSmsManuelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsManuelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult SendSmsManuelResult;
        
        public SendSmsManuelResponse()
        {
        }
        
        public SendSmsManuelResponse(SMSService.ServiceResult SendSmsManuelResult)
        {
            this.SendSmsManuelResult = SendSmsManuelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailManuel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailManuelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.AuthServiceRequestVM auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SMSService.SendEmailVM reqEmail;
        
        public SendEmailManuelRequest()
        {
        }
        
        public SendEmailManuelRequest(SMSService.AuthServiceRequestVM auth, SMSService.SendEmailVM reqEmail)
        {
            this.auth = auth;
            this.reqEmail = reqEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailManuelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailManuelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult SendEmailManuelResult;
        
        public SendEmailManuelResponse()
        {
        }
        
        public SendEmailManuelResponse(SMSService.ServiceResult SendEmailManuelResult)
        {
            this.SendEmailManuelResult = SendEmailManuelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaymentChannelServiceLoguOlustur", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaymentChannelServiceLoguOlusturRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public SMSService.LogPcrVM logreq;
        
        public PaymentChannelServiceLoguOlusturRequest()
        {
        }
        
        public PaymentChannelServiceLoguOlusturRequest(string CtWcfusername, string CtWcfpassword, SMSService.LogPcrVM logreq)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
            this.logreq = logreq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaymentChannelServiceLoguOlusturResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaymentChannelServiceLoguOlusturResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult PaymentChannelServiceLoguOlusturResult;
        
        public PaymentChannelServiceLoguOlusturResponse()
        {
        }
        
        public PaymentChannelServiceLoguOlusturResponse(SMSService.ServiceResult PaymentChannelServiceLoguOlusturResult)
        {
            this.PaymentChannelServiceLoguOlusturResult = PaymentChannelServiceLoguOlusturResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HataLoguOlustur", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HataLoguOlusturRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Exception ex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public SMSService.LogVM logreq;
        
        public HataLoguOlusturRequest()
        {
        }
        
        public HataLoguOlusturRequest(string CtWcfusername, string CtWcfpassword, System.Exception ex, SMSService.LogVM logreq)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
            this.ex = ex;
            this.logreq = logreq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HataLoguOlusturResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HataLoguOlusturResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult HataLoguOlusturResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Exception ex;
        
        public HataLoguOlusturResponse()
        {
        }
        
        public HataLoguOlusturResponse(SMSService.ServiceResult HataLoguOlusturResult, System.Exception ex)
        {
            this.HataLoguOlusturResult = HataLoguOlusturResult;
            this.ex = ex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InfoLoguOlustur", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InfoLoguOlusturRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public SMSService.LogVM logreq;
        
        public InfoLoguOlusturRequest()
        {
        }
        
        public InfoLoguOlusturRequest(string CtWcfusername, string CtWcfpassword, SMSService.LogVM logreq)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
            this.logreq = logreq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InfoLoguOlusturResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InfoLoguOlusturResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult InfoLoguOlusturResult;
        
        public InfoLoguOlusturResponse()
        {
        }
        
        public InfoLoguOlusturResponse(SMSService.ServiceResult InfoLoguOlusturResult)
        {
            this.InfoLoguOlusturResult = InfoLoguOlusturResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDashboard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDashboardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public SMSService.DashboardRequestVM req;
        
        public GetDashboardRequest()
        {
        }
        
        public GetDashboardRequest(string CtWcfusername, string CtWcfpassword, SMSService.DashboardRequestVM req)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDashboardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDashboardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult GetDashboardResult;
        
        public GetDashboardResponse()
        {
        }
        
        public GetDashboardResponse(SMSService.ServiceResult GetDashboardResult)
        {
            this.GetDashboardResult = GetDashboardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDashboardShopperTopList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDashboardShopperTopListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CtWcfusername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CtWcfpassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public SMSService.DashboardRequestVM req;
        
        public GetDashboardShopperTopListRequest()
        {
        }
        
        public GetDashboardShopperTopListRequest(string CtWcfusername, string CtWcfpassword, SMSService.DashboardRequestVM req)
        {
            this.CtWcfusername = CtWcfusername;
            this.CtWcfpassword = CtWcfpassword;
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDashboardShopperTopListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDashboardShopperTopListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SMSService.ServiceResult GetDashboardShopperTopListResult;
        
        public GetDashboardShopperTopListResponse()
        {
        }
        
        public GetDashboardShopperTopListResponse(SMSService.ServiceResult GetDashboardShopperTopListResult)
        {
            this.GetDashboardShopperTopListResult = GetDashboardShopperTopListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IAllGeneralServiceChannel : SMSService.IAllGeneralService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class AllGeneralServiceClient : System.ServiceModel.ClientBase<SMSService.IAllGeneralService>, SMSService.IAllGeneralService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AllGeneralServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AllGeneralServiceClient.GetBindingForEndpoint(endpointConfiguration), AllGeneralServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AllGeneralServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AllGeneralServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AllGeneralServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AllGeneralServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AllGeneralServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SMSService.BankListResponse> BankListAsync(SMSService.BankListRequest request)
        {
            return base.Channel.BankListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.GetBankResponse> GetBankAsync(SMSService.GetBankRequest request)
        {
            return base.Channel.GetBankAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.CurrencyListResponse> CurrencyListAsync(SMSService.CurrencyListRequest request)
        {
            return base.Channel.CurrencyListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.GetCurrencyResponse> GetCurrencyAsync(SMSService.GetCurrencyRequest request)
        {
            return base.Channel.GetCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.LanguageListResponse> LanguageListAsync(SMSService.LanguageListRequest request)
        {
            return base.Channel.LanguageListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.CountryListResponse> CountryListAsync(SMSService.CountryListRequest request)
        {
            return base.Channel.CountryListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.CityListResponse> CityListAsync(SMSService.CityListRequest request)
        {
            return base.Channel.CityListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.CompanyListResponse> CompanyListAsync(SMSService.CompanyListRequest request)
        {
            return base.Channel.CompanyListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.SendSmsManuelResponse> SendSmsManuelAsync(SMSService.SendSmsManuelRequest request)
        {
            return base.Channel.SendSmsManuelAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.SendEmailManuelResponse> SendEmailManuelAsync(SMSService.SendEmailManuelRequest request)
        {
            return base.Channel.SendEmailManuelAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.PaymentChannelServiceLoguOlusturResponse> PaymentChannelServiceLoguOlusturAsync(SMSService.PaymentChannelServiceLoguOlusturRequest request)
        {
            return base.Channel.PaymentChannelServiceLoguOlusturAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.HataLoguOlusturResponse> HataLoguOlusturAsync(SMSService.HataLoguOlusturRequest request)
        {
            return base.Channel.HataLoguOlusturAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.InfoLoguOlusturResponse> InfoLoguOlusturAsync(SMSService.InfoLoguOlusturRequest request)
        {
            return base.Channel.InfoLoguOlusturAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.GetDashboardResponse> GetDashboardAsync(SMSService.GetDashboardRequest request)
        {
            return base.Channel.GetDashboardAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSService.GetDashboardShopperTopListResponse> GetDashboardShopperTopListAsync(SMSService.GetDashboardShopperTopListRequest request)
        {
            return base.Channel.GetDashboardShopperTopListAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAllGeneralService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IAllGeneralService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAllGeneralService))
            {
                return new System.ServiceModel.EndpointAddress("http://api.haso.com.tr/General/AllGeneralService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IAllGeneralService))
            {
                return new System.ServiceModel.EndpointAddress("https://api.haso.com.tr/General/AllGeneralService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAllGeneralService,
            
            BasicHttpsBinding_IAllGeneralService,
        }
    }
}
